name: Build Desktop App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        working-directory: nextjs_space
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Remove symlink
        run: rm -f yarn.lock || true
        shell: bash terminal
      - run: yarn install
      - run: yarn prisma generate
      - run: yarn build
        env:
          DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
      - run: yarn add electron electron-builder --dev
      - run: yarn electron-builder --win --publish never
        if: matrix.os == 'windows-latest'
      - run: yarn electron-builder --mac --publish never
        if: matrix.os == 'macos-latest'
      - run: yarn electron-builder --linux --publish never
        if: matrix.os == 'ubuntu-latest'
      - uses: actions/upload-artifact@v4
        with:
          name: SuperPOS-${{ matrix.os }}
          path: nextjs_space/dist/*
